name: Extract Jira Ticket from Branch

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - '**'

jobs:
  extract-jira-ticket:
    name: Extract Jira Ticket ID from Branch Name
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Jira Ticket ID from branch name
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Branch name: $BRANCH_NAME"
          # Regex for JIRA ticket (e.g., PROJ-1234)
          if [[ "$BRANCH_NAME" =~ ([A-Z]+-[0-9]+) ]]; then
            JIRA_ID="${BASH_REMATCH[1]}"
            echo "Jira Ticket ID: $JIRA_ID"
            echo "jira_id=$JIRA_ID" >> $GITHUB_OUTPUT
          else
            echo "No Jira Ticket ID found in branch name."
            exit 1
          fi

      - name: Use Jira Ticket ID
        run: |
          echo "Jira Ticket ID is ${{ steps.extract.outputs.jira_id }}"