name: Extract Jira Ticket from Branch.

on:
  pull_request:
    branches:
      - '*'

jobs:
  extract-jira-ticket:
    name: Extract Jira Ticket ID from Branch Name
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Jira Ticket ID from branch name
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          echo "Branch name: $BRANCH_NAME"
          fi

      - name: Use Jira Ticket ID
        run: |
          echo "Jira Ticket ID is ${{ steps.extract.outputs.jira_id }}"
