name: Extract Jira Ticket from Branch.

on:
  pull_request:
    branches:
      - '*'

jobs:
  extract-jira-ticket:
    name: Extract Jira Ticket ID from Branch Name
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Jira Ticket ID from branch name
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          echo "Branch name: $BRANCH_NAME"
          fi

      - name: Give branch name to AI agent to exctract the jira id
        run: |
          echo "Here I give {{BRANCH_NAME}} to AI agent written in C# to extract the Jira ID and return it as output (id and relevant information)"

      - name: Use Jira Ticket ID
        run: |
          echo "Jira Ticket ID is defined and ai agent finds relevant information from existing files and compares it to extracted information"
